# Generated by Django 4.1 on 2023-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('V', 'Vegetarian'), ('NV', 'Non Vegetarian'), ('VG', 'Vegan')], default='', max_length=2),
        ),
        migrations.DeleteModel(
            name='Recipe_Category',
        ),
    ]
